/**
 * Minimal invoice PDF helper (pdfkit). Returns a Buffer.
 */
import PDFDocument from 'pdfkit';
import { formatINR } from './money.js';

/**
 * @param {{
 *   number: string,
 *   clubName?: string,
 *   customerName?: string,
 *   localDate?: string,
 *   status?: string,
 *   lines?: Array<{ description: string, qty: number, unitPricePaise: number, totalPaise: number }>,
 *   totals?: { subtotalPaise?: number, taxPaise?: number, totalPaise?: number, paidPaise?: number, duePaise?: number },
 * }} invoice
 * @returns {Promise<Buffer>}
 */
export function buildInvoicePdf(invoice) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const club = invoice.clubName || 'Arambh Sports Arena';
    doc.fontSize(18).text(club, { align: 'left' });
    doc.moveDown(0.5);
    doc.fontSize(14).text(`Invoice ${invoice.number || ''}`);
    doc.fontSize(10).fillColor('#444');
    doc.text(`Date: ${invoice.localDate || ''}`);
    doc.text(`Customer: ${invoice.customerName || '—'}`);
    doc.text(`Status: ${invoice.status || ''}`);
    doc.moveDown();
    doc.fillColor('#000');

    doc.fontSize(11).text('Lines', { underline: true });
    doc.moveDown(0.3);
    for (const line of invoice.lines || []) {
      doc
        .fontSize(10)
        .text(
          `${line.description}  ×${line.qty}  @ ${formatINR(line.unitPricePaise || 0)}  = ${formatINR(line.totalPaise || 0)}`,
        );
    }

    const t = invoice.totals || {};
    doc.moveDown();
    doc.fontSize(11).text(`Subtotal: ${formatINR(t.subtotalPaise || 0)}`);
    doc.text(`Tax: ${formatINR(t.taxPaise || 0)}`);
    doc.fontSize(12).text(`Total: ${formatINR(t.totalPaise || 0)}`, { underline: true });
    doc.fontSize(10).text(`Paid: ${formatINR(t.paidPaise || 0)}  ·  Due: ${formatINR(t.duePaise || 0)}`);

    doc.moveDown(2);
    doc.fontSize(9).fillColor('#888').text('Generated by Arambh Sports Arena', { align: 'center' });

    doc.end();
  });
}

/**
 * Placeholder PDF when full invoice data is unavailable.
 * @param {string} [title]
 * @returns {Promise<Buffer>}
 */
export function buildPlaceholderPdf(title = 'Arambh Sports Arena — document') {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    doc.fontSize(16).text(title);
    doc.fontSize(10).text('PDF placeholder');
    doc.end();
  });
}

export default { buildInvoicePdf, buildPlaceholderPdf };
